version: 0.2
os: linux
files:
  - source: /src/index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root